#!/usr/bin/env python
import os
import sys
from llpy16.compiler import do_compile


if __name__ == '__main__':
    with open(sys.argv[1]) as fobj:
        do_compile(fobj.read(), [os.path.dirname(sys.argv[1])])

